iris-res: ":iris-resources" {
  "Shared resources"
  "strings and drawables"
}
iris-base: ":iris-base" {
  "Code shared everywhere"
}
iris-data: ":iris-data" {
  "Data Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  "CRUD: Repositories & DataSources"
}
iris-domain: ":iris-domain" {
  "Domain Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  "Business logic & rules"
}
iris-common-ui: ":iris-common-ui" {
  "UI components bundled with domain logic"
}
iris-nav: ":iris-navigation" {
  "Screen destinations"
  "Navigation logic"
}
iris-design: ":iris-design" {
  "Iris design system"
}
screens: ":screen/feature" {
  "UI Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  ":screen-home"
  ":feature-google-drive"
  ":screen-abc"
  ":feature-xyz"
}
app: ":app" {
  "App monolith"
  "Wires the implementation of all screens"
}

iris-data -> iris-base
iris-domain -> iris-data
iris-domain -> iris-base

iris-design -> iris-res
iris-nav -> iris-domain
iris-nav -> iris-design

iris-common-ui -> iris-nav

screens -> iris-common-ui
screens -> iris-nav
screens -> iris-res

app -> screens
